apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-cache
  template:
    metadata:
      labels:
        app: order-cache
    spec:
      containers:
        - name: order-cache
          image: redis:latest
          ports:
            - containerPort: 6379