apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: mennan0809/api-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: SERVICES_USER-SERVICE_URL
              value: "http://user-service.default.svc.cluster.local:8080"
            - name: SERVICES_PRODUCT-SERVICE_URL
              value: "http://product-service.default.svc.cluster.local:8080"
            - name: SERVICES_PAYMENT-SERVICE_URL
              value: "http://payment-service.default.svc.cluster.local:8080"
            - name: SERVICES_ORDER-SERVICE_URL
              value: "http://order-service.default.svc.cluster.local:8080"
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_MAIN_WEB_APPLICATION_TYPE
              value: reactive
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_ID
              value: user-service
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
              value: http://user-service:8080
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
              value: Path=/users/**
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_ID
              value: product-service
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_URI
              value: http://product-service:8080
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0
              value: Path=/products/**

            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_ID
              value: order-service
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_URI
              value: http://order-service:8080
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0
              value: Path=/orders/**

            - name: SPRING_CLOUD_GATEWAY_ROUTES_3_ID
              value: payment-service
            - name: SPRING_CLOUD_GATEWAY_ROUTES_3_URI
              value: http://payment-service:8080
            - name: SPRING_CLOUD_GATEWAY_ROUTES_3_PREDICATES_0
              value: Path=/payments/**

            - name: SPRING_CLOUD_GATEWAY_ROUTES_4_ID
              value: order-service
            - name: SPRING_CLOUD_GATEWAY_ROUTES_4_URI
              value: http://order-service:8080
            - name: SPRING_CLOUD_GATEWAY_ROUTES_4_PREDICATES_0
              value: Path=/carts/**